const dadisms = [
  { id: 0, text: '"Curved glass"' },
  { id: 1, text: '"Bend over..."' },
  { id: 2, text: '"What a peculiar shaped..."' },
  { id: 3, text: '"90% of your heat through your head"' },
  { id: 4, text: '"... pick it up"' },
  { id: 5, text: '"Barb"' },
  { id: 6, text: "Putting another log on the fire" },
  { id: 7, text: '"Tegnomi"' },
  { id: 8, text: '"I’ll be back home in ten minutes, Barb"' },
  { id: 9, text: '"Let’s go the scenic route"' },
  { id: 10, text: '"I know a short cut!"' },
  { id: 11, text: '"Were you born in a barn?"' },
  { id: 12, text: '"One of your best yet"' },
  { id: 13, text: 'Calling dogs "he" and cats "she"' },
  { id: 14, text: '"Better..!"' },
  { id: 15, text: '"London is 2 degrees warmer"' },
  { id: 16, text: '"Shingles!"' },
  { id: 17, text: "Coughs" },
  { id: 18, text: '"I used to cycle to Honilee"' },
  { id: 19, text: '"When I was younger I played rugby"' },
  { id: 20, text: '"...your mom..."' },
  { id: 21, text: '"Shame for any food to go to waste"' },
  { id: 22, text: "Having headphones in" },
  { id: 23, text: "Reading a book at your graduation" },
  { id: 24, text: '"Oh my coffee has gotten cold"' },
  { id: 25, text: '"Has Bobby been walked yet?"' },
  { id: 26, text: '"Diamonds are forever"' },
  { id: 27, text: '"We’re on the road to nowhere"' },
  { id: 28, text: "Playing a tune on the recorder" },
  { id: 29, text: "Showing off his pottery collection"}
];

export default dadisms;
